### ISSUE TITLE
Erstelle Use Cases Overview Diagram

### ISSUE THREAD

**Issue by Robin-Kierstein** [Robin-Kierstein/SoftwareHeros#2]
- [x] Erstellen von Use Cases Overview Diagram
- [x] Im Wiki hochladen

**Comment by FurkanAslanmirza** [comment]
[App Use Case Diagramm.pdf](https://github.com/Robin-Kierstein/SoftwareHeros/files/11416003/App.Use.Case.Diagramm.pdf)
