### ISSUE TITLE
Erstelle Detailed Use Cases

### ISSUE THREAD

**Issue by Robin-Kierstein** [Robin-Kierstein/SoftwareHeros#3]
- [x] Erstellen von Detailed Use Cases
- [x] Im Wiki hochladen

**Comment by FurkanAslanmirza** [comment]
[Manage Authorization Use Case Diagramm.pdf](https://github.com/Robin-Kierstein/SoftwareHeros/files/11416006/Manage.Authorization.Use.Case.Diagramm.pdf)

**Comment by FurkanAslanmirza** [comment]
[Manage Authorization Req. Documentation.docx](https://github.com/Robin-Kierstein/SoftwareHeros/files/11416007/Manage.Authorization.Req.Documentation.docx)
