### ISSUE TITLE
Erstelle Quality Requirements & Constraints

### ISSUE THREAD

**Issue by Robin-Kierstein** [Robin-Kierstein/SoftwareHeros#4]
- [x] Erstellen von Quality Requirements & Constraints
- [x] Im Wiki hochladen

**Comment by FurkanAslanmirza** [comment]
[Manage Authorization Quality Req. & Cons..docx](https://github.com/Robin-Kierstein/SoftwareHeros/files/11416008/Manage.Authorization.Quality.Req.Cons.docx)
